### ISSUE TITLE
Impossible d'insérer plusieurs médias

### ISSUE THREAD

**Issue by franck-tomek** [franck-paul/multipleMedia#3]
J'ai un souci d’insertion avec multipleMedia (testé sur 2 installs) : quand je clique sur Insérer, ça ne fonctionne pas et j’ai des erreurs dans la console.

```
Uncaught TypeError: e is undefined
    <anonymous> https://urldeladmin/index.php?pf=multipleMedia/js/popup_media_prefs.js&v=4.0:1
    <anonymous> https://urldeladmin/index.php?pf=multipleMedia/js/popup_media_prefs.js&v=4.0:1
    jQuery 8
    <anonymous> https://urldeladmin/index.php?pf=multipleMedia/js/popup_media_prefs.js&v=4.0:1
    jQuery 13
```
DC 2.27.3 / multipleMedia 4.0

**Comment by franck-paul** [comment]
Bon, déjà la 5.2 fonctionne comme attendu sur une 2.28 et la 4.0 fonctionne aussi comme attendu sur une 2.27.3 (chez moi).

T'aurais pas un adblock ou équivalent qui foutrait le dawa des fois ?

**Comment by franck-tomek** [comment]
µblock est désactivé par défaut pour l'admin… faut que je teste en désactivant les modules.

**Comment by franck-tomek** [comment]
Bon, c'est bien un truc / module dans Firefox (je vais tâcher de trouver quoi), j'ai testé dans Safari et ça fonctionne comme attendu. Désolé pour le bruit.
