### ISSUE TITLE
Impossible d'insérer sous Firefox, Safari, Vivaldi, Tor Browser

### ISSUE THREAD

**Issue by franck-tomek** [franck-paul/multipleMedia#6]
Je sélectionne tous les médias dans la fenêtre qui s'ouvre, je clique sur "Choisir les médias sélectionnés" et la fenêtre se recharge en désélectionnant les médias précédemment sélectionnés et en affichant dans la console ce qui suit. 

J'ai testé avec tous les navigateurs à ma dispo sur mon Mac, il y a une erreur similaire sur FF & Tor Browser (logique) : 

```
Uncaught TypeError: document.querySelector(...) is null
    <anonymous> https://domainedusite.net/admin/index.php?pf=multipleMedia/js/dialog_media_manager.js&v=5.5:1
    <anonymous> https://domainedusite.net/admin/index.php?pf=multipleMedia/js/dialog_media_manager.js&v=5.5:1
    jQuery 2
        dispatch
        handle
```

Et une erreur qui ne s'affiche qu'en flash sur Safari / Vivaldi et que je ne peux pas récupérer.

La 2e fenêtre pour définir la façon d'insérer n'apparaît donc pas.

**Comment by franck-paul** [comment]
Quelle version de DC, la dernière ?

**Comment by franck-tomek** [comment]
Ah oui pardon : DC 2.31.1, MultipleMedia 5.5

**Comment by franck-paul** [comment]
Je confirme, y'a un bug depuis peu.
Je corrige et je publie une nouvelle version

**Comment by franck-tomek** [comment]
Je me permets de continuer sur ce ticket : j'ai mis à jour avec la 5.5.1, la 2e fenêtre apparaît bien maintenant, en revanche quand je fais "Insérer", elle se ferme (logique), mais le code n'est pas inséré dans le billet.

**Comment by franck-paul** [comment]
M'enfin, j'ai testé et ça marche chez moi !?!

Et je viens de refaire le test depuis un autre répertoire (des fois que), et tout est ok.

**Comment by franck-tomek** [comment]
Grompf. Ça n'est pourtant pas sur mon site habituel (des bugs tordus). Je reteste un peu plus tard, et ailleurs. Je te tiens au courant.

**Comment by franck-tomek** [comment]
C'est tout bon maintenant, j'ai retesté sur le même site. Va comprendre.
