### ISSUE TITLE
Insertions

### ISSUE THREAD

**Issue by jemattarde** [franck-paul/multipleMedia#7]
Bonjour,
Pour info, la dernière mise à jour Dotclear a rendu caduque le plugin multipleMedia, il n'est plus possible d'insérer des images avec lien vers l'image originale directement via l'interface.

**Comment by jemattarde** [comment]
D'ailleurs, c'est le même problème que ce soit avec MultipleMedia ou avec l'ajout classique d'image : moi je ne peux plus ajouter d'image avec lien vers l'originale.

**Comment by franck-paul** [comment]
J'ai l'impression que ça n'est pas lié du tout au plugin, je me trompe ?

Quoi qu'il en soit, un peu plus de contexte aiderait à comprendre le problème, merci de donner des détails.
